modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="advancedsticks:iron_stick_diamond_pickaxe"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AdvancedSticks.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Advanced Sticks is a mod that adds new sticks to modify the default weapons and tools! Every Stick has other values that adds to the normal tool.'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

