modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks/issues"

[[mods]]
modId="advancedsticks"
version="2.2.6"
displayName="AdvancedSticks"
itemIcon="advancedsticks:diamond_stick"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AdvancedSticks.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''Advanced Sticks is a mod that adds new sticks to modify the default weapons and tools! Every Stick has other values that adds to the normal tool.'''

[[dependencies.advancedsticks]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.advancedsticks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
