package xxrexraptorxx.advancedsticks.main;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.CreativeModeTabEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import xxrexraptorxx.advancedsticks.utils.Config;
import xxrexraptorxx.advancedsticks.utils.ModItemProperties;

/**
 * @author XxRexRaptorxX (RexRaptor)
 * @projectPage https://www.curseforge.com/minecraft/mc-mods/advanced-sticks
 **/
@Mod(References.MODID)
public class AdvancedSticks {

    public static final Logger LOGGER = LogManager.getLogger();
    private static final ResourceLocation CREATIVE_TAB = new ResourceLocation(References.MODID, "tab");


    public AdvancedSticks() {
        Mod.EventBusSubscriber.Bus.MOD.bus().get().register(AdvancedSticks.class);
        IEventBus eventBus = FMLJavaModLoadingContext.get().getModEventBus();

        Config.init();
        ModItems.init();

        eventBus.addListener(this::clientSetup);
    }


    private void clientSetup(final FMLClientSetupEvent event) {
        ModItemProperties.addItemProperties();
    }


    //Creative Tab
    @SubscribeEvent
    public static void registerTabs(final CreativeModeTabEvent.Register event) {
        event.registerCreativeModeTab(CREATIVE_TAB, (cf) -> cf.icon(() -> new ItemStack(ModItems.IRON_STICK_DIAMOND_PICKAXE.get()))
                .title(Component.translatable("itemGroup." + References.MODID + "_tab")).displayItems((p_270258_, output) -> {
                    output.accept(ModItems.BONE_STICK.get());
                    output.accept(ModItems.IRON_STICK.get());
                    output.accept(ModItems.GOLD_STICK.get());
                    output.accept(ModItems.COPPER_STICK.get());
                    output.accept(ModItems.EMERALD_STICK.get());
                    output.accept(ModItems.AMETHYST_STICK.get());
                    output.accept(ModItems.DIAMOND_STICK.get());
                    output.accept(ModItems.NETHERITE_STICK.get());
                    output.accept(ModItems.ENCHANTED_STICK.get());
                    output.accept(ModItems.ADVANCED_STICK.get());

                    output.accept(ModItems.IRON_BOW.get());
                    output.accept(ModItems.GOLD_BOW.get());
                    output.accept(ModItems.DIAMOND_BOW.get());
                    output.accept(ModItems.NETHERITE_BOW.get());

                    output.accept(ModItems.BONE_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.BONE_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_WOOD_AXE.get());
                    output.accept(ModItems.BONE_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_WOOD_HOE.get());
                    output.accept(ModItems.IRON_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.IRON_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_WOOD_AXE.get());
                    output.accept(ModItems.IRON_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_WOOD_HOE.get());
                    output.accept(ModItems.COPPER_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_WOOD_AXE.get());
                    output.accept(ModItems.COPPER_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_WOOD_HOE.get());
                    output.accept(ModItems.GOLD_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_WOOD_AXE.get());
                    output.accept(ModItems.GOLD_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_WOOD_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_WOOD_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_WOOD_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_WOOD_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_WOOD_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_WOOD_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_WOOD_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_WOOD_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_WOOD_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_WOOD_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_WOOD_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_WOOD_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_WOOD_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_WOOD_HOE.get());
                    output.accept(ModItems.END_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.END_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.END_STICK_WOOD_AXE.get());
                    output.accept(ModItems.END_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.END_STICK_WOOD_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_WOOD_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_WOOD_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_WOOD_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_WOOD_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_WOOD_HOE.get());

                    output.accept(ModItems.BONE_STICK_STONE_SWORD.get());
                    output.accept(ModItems.BONE_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_STONE_AXE.get());
                    output.accept(ModItems.BONE_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_STONE_HOE.get());
                    output.accept(ModItems.IRON_STICK_STONE_SWORD.get());
                    output.accept(ModItems.IRON_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_STONE_AXE.get());
                    output.accept(ModItems.IRON_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_STONE_HOE.get());
                    output.accept(ModItems.COPPER_STICK_STONE_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_STONE_AXE.get());
                    output.accept(ModItems.COPPER_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_STONE_HOE.get());
                    output.accept(ModItems.GOLD_STICK_STONE_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_STONE_AXE.get());
                    output.accept(ModItems.GOLD_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_STONE_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_STONE_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_STONE_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_STONE_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_STONE_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_STONE_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_STONE_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_STONE_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_STONE_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_STONE_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_STONE_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_STONE_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_STONE_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_STONE_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_STONE_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_STONE_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_STONE_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_STONE_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_STONE_HOE.get());
                    output.accept(ModItems.END_STICK_STONE_SWORD.get());
                    output.accept(ModItems.END_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.END_STICK_STONE_AXE.get());
                    output.accept(ModItems.END_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.END_STICK_STONE_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_STONE_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_STONE_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_STONE_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_STONE_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_STONE_HOE.get());

                    output.accept(ModItems.BONE_STICK_IRON_SWORD.get());
                    output.accept(ModItems.BONE_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_IRON_AXE.get());
                    output.accept(ModItems.BONE_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_IRON_HOE.get());
                    output.accept(ModItems.IRON_STICK_IRON_SWORD.get());
                    output.accept(ModItems.IRON_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_IRON_AXE.get());
                    output.accept(ModItems.IRON_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_IRON_HOE.get());
                    output.accept(ModItems.COPPER_STICK_IRON_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_IRON_AXE.get());
                    output.accept(ModItems.COPPER_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_IRON_HOE.get());
                    output.accept(ModItems.GOLD_STICK_IRON_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_IRON_AXE.get());
                    output.accept(ModItems.GOLD_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_IRON_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_IRON_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_IRON_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_IRON_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_IRON_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_IRON_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_IRON_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_IRON_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_IRON_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_IRON_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_IRON_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_IRON_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_IRON_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_IRON_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_IRON_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_IRON_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_IRON_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_IRON_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_IRON_HOE.get());
                    output.accept(ModItems.END_STICK_IRON_SWORD.get());
                    output.accept(ModItems.END_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.END_STICK_IRON_AXE.get());
                    output.accept(ModItems.END_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.END_STICK_IRON_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_IRON_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_IRON_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_IRON_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_IRON_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_IRON_HOE.get());

                    output.accept(ModItems.BONE_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.BONE_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_GOLD_AXE.get());
                    output.accept(ModItems.BONE_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_GOLD_HOE.get());
                    output.accept(ModItems.IRON_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.IRON_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_GOLD_AXE.get());
                    output.accept(ModItems.IRON_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_GOLD_HOE.get());
                    output.accept(ModItems.COPPER_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_GOLD_AXE.get());
                    output.accept(ModItems.COPPER_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_GOLD_HOE.get());
                    output.accept(ModItems.GOLD_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_GOLD_AXE.get());
                    output.accept(ModItems.GOLD_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_GOLD_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_GOLD_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_GOLD_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_GOLD_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_GOLD_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_GOLD_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_GOLD_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_GOLD_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_GOLD_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_GOLD_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_GOLD_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_GOLD_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_GOLD_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_GOLD_HOE.get());
                    output.accept(ModItems.END_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.END_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.END_STICK_GOLD_AXE.get());
                    output.accept(ModItems.END_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.END_STICK_GOLD_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_GOLD_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_GOLD_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_GOLD_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_GOLD_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_GOLD_HOE.get());

                    output.accept(ModItems.BONE_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.BONE_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.BONE_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.IRON_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.IRON_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.IRON_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.COPPER_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.COPPER_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.GOLD_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.GOLD_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_DIAMOND_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.END_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.END_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.END_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.END_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.END_STICK_DIAMOND_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_DIAMOND_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_DIAMOND_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_DIAMOND_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_DIAMOND_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_DIAMOND_HOE.get());

                    output.accept(ModItems.BONE_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.BONE_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.BONE_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.BONE_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.BONE_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.IRON_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.IRON_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.IRON_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.IRON_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.IRON_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.COPPER_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.COPPER_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.COPPER_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.COPPER_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.COPPER_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.GOLD_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.GOLD_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.GOLD_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.GOLD_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.GOLD_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.DIAMOND_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.DIAMOND_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.DIAMOND_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.DIAMOND_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.DIAMOND_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.EMERALD_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.EMERALD_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.EMERALD_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.EMERALD_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.EMERALD_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.AMETHYST_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.AMETHYST_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.AMETHYST_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.AMETHYST_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.AMETHYST_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.NETHERITE_STICK_NETHERITE_SWORD .get());
                    output.accept(ModItems.NETHERITE_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.NETHERITE_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.NETHERITE_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.NETHERITE_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.ADVANCED_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.ADVANCED_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.ADVANCED_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.ADVANCED_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.ADVANCED_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.BLAZE_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.BLAZE_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.BLAZE_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.BLAZE_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.BLAZE_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.END_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.END_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.END_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.END_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.END_STICK_NETHERITE_HOE.get());
                    output.accept(ModItems.ENCHANTED_STICK_NETHERITE_SWORD.get());
                    output.accept(ModItems.ENCHANTED_STICK_NETHERITE_PICKAXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_NETHERITE_AXE.get());
                    output.accept(ModItems.ENCHANTED_STICK_NETHERITE_SHOVEL.get());
                    output.accept(ModItems.ENCHANTED_STICK_NETHERITE_HOE.get());
                })
        );
    }
}