modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="advancedtools:iron_stick_diamond_pickaxe"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/AdvancedSticks/refs/heads/master/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-sticks"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Lets you build tools and weapons from components of many different materials with different stats, properties and effects!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/smithing_table_top.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"

